#-------------------------------
# General Site Settings
title: Change It Up
logo: # You can add own logo. For example '/images/logo.png'.
description: Hally is a modern and minimal Jekyll theme for sharing your ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Howard Burns
  image: '/images/01.jpg'
  avatar: '/images/01.jpg'
  description: My name is Howard Burns. I'm a freelance photographer based in Denver. I like being free and enjoying every moment.


#-------------------------------
# Contact links

# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
contact:
- {name: "Twitter", icon: "ion-logo-twitter", link: "https://twitter.com"}
- {name: "Facebook", icon: "ion-logo-facebook", link: "https://facebook.com"}
- {name: "Dribbble", icon: "ion-logo-dribbble", link: "https://dribbble.com"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Newsletter
mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp-description: Subscribe to our newsletter and we’ll send you the emails of latest posts.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  # This does not work with GitHub pages
  # - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
